"""structured content persistence schema

Revision ID: 0002_structured_content_persistence_schema
Revises: 0001_foundation_schema
Create Date: 2026-07-22 00:00:00.000000
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0002_structured_content_persistence_schema"
down_revision: Union[str, None] = "0001_foundation_schema"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _id():
    return sa.Column("id", sa.String(), nullable=False)


def upgrade() -> None:
    op.create_table(
        "structured_content_candidates",
        _id(), sa.Column("candidate_id", sa.String(255), nullable=False), sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("lineage_key", sa.String(255), nullable=False), sa.Column("schema_id", sa.String(255), nullable=False), sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("source_file_ref", sa.String(1024)), sa.Column("processing_run_ref", sa.String(1024)), sa.Column("raw_result_ref", sa.String(1024)), sa.Column("structured_processing_result_ref", sa.String(1024)),
        sa.Column("transformer_ref", sa.String(255)), sa.Column("transformation_policy_ref", sa.String(255)), sa.Column("recovery_state", sa.String(50), nullable=False),
        sa.Column("total_page_count", sa.Integer(), nullable=False), sa.Column("complete_page_count", sa.Integer(), nullable=False), sa.Column("degraded_page_count", sa.Integer(), nullable=False),
        sa.Column("no_usable_page_count", sa.Integer(), nullable=False), sa.Column("unavailable_page_count", sa.Integer(), nullable=False), sa.Column("unsupported_page_count", sa.Integer(), nullable=False),
        sa.Column("extensions_json", sa.Text()), sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"), sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="RESTRICT"),
        sa.UniqueConstraint("candidate_id", name="uq_sc_candidates_candidate_id"), sa.UniqueConstraint("document_id", "candidate_id", name="uq_sc_candidates_document_candidate"), sa.UniqueConstraint("id", "document_id", name="uq_sc_candidates_id_document"),
        sa.CheckConstraint("candidate_id <> ''", name="ck_sc_candidates_candidate_id_nonempty"), sa.CheckConstraint("lineage_key <> ''", name="ck_sc_candidates_lineage_key_nonempty"), sa.CheckConstraint("schema_version >= 0", name="ck_sc_candidates_schema_version_nonnegative"),
        sa.CheckConstraint("total_page_count >= 0", name="ck_sc_candidates_total_pages_nonnegative"), sa.CheckConstraint("complete_page_count >= 0", name="ck_sc_candidates_complete_pages_nonnegative"), sa.CheckConstraint("degraded_page_count >= 0", name="ck_sc_candidates_degraded_pages_nonnegative"), sa.CheckConstraint("no_usable_page_count >= 0", name="ck_sc_candidates_no_usable_pages_nonnegative"), sa.CheckConstraint("unavailable_page_count >= 0", name="ck_sc_candidates_unavailable_pages_nonnegative"), sa.CheckConstraint("unsupported_page_count >= 0", name="ck_sc_candidates_unsupported_pages_nonnegative"),
    )
    op.create_index("ix_sc_candidates_document_id", "structured_content_candidates", ["document_id"]); op.create_index("ix_sc_candidates_lineage_key", "structured_content_candidates", ["lineage_key"])
    op.create_table("structured_content_pages", _id(), sa.Column("candidate_id", sa.String(), nullable=False), sa.Column("page_id", sa.String(255), nullable=False), sa.Column("page_order", sa.Integer(), nullable=False), sa.Column("source_page_index", sa.Integer(), nullable=False), sa.Column("recovery_state", sa.String(50), nullable=False), sa.Column("page_label", sa.String(255)), sa.Column("width", sa.Float()), sa.Column("height", sa.Float()), sa.Column("dimension_unit", sa.String(50)), sa.Column("coordinate_origin", sa.String(50)), sa.Column("coordinate_unit", sa.String(50)), sa.Column("rotation_applied", sa.Boolean()), sa.Column("rotation_degrees", sa.Float()), sa.Column("extensions_json", sa.Text()), sa.PrimaryKeyConstraint("id"), sa.ForeignKeyConstraint(["candidate_id"], ["structured_content_candidates.id"], ondelete="CASCADE"), sa.UniqueConstraint("candidate_id", "page_id", name="uq_sc_pages_candidate_page_id"), sa.UniqueConstraint("candidate_id", "page_order", name="uq_sc_pages_candidate_page_order"), sa.UniqueConstraint("id", "candidate_id", name="uq_sc_pages_id_candidate"), sa.CheckConstraint("page_order >= 0", name="ck_sc_pages_page_order_nonnegative"), sa.CheckConstraint("source_page_index >= 0", name="ck_sc_pages_source_page_index_nonnegative"))
    op.create_index("ix_sc_pages_candidate_order", "structured_content_pages", ["candidate_id", "page_order"])
    op.create_table("structured_content_nodes", _id(), sa.Column("candidate_id", sa.String(), nullable=False), sa.Column("page_id", sa.String(), nullable=False), sa.Column("node_id", sa.String(255), nullable=False), sa.Column("lineage_key", sa.String(255), nullable=False), sa.Column("node_type", sa.String(50), nullable=False), sa.Column("parent_node_id", sa.String()), sa.Column("sibling_order", sa.Integer(), nullable=False), sa.Column("text", sa.Text()), sa.Column("recovery_state", sa.String(50), nullable=False), sa.Column("source_page_index", sa.Integer()), sa.Column("bbox_left", sa.Float()), sa.Column("bbox_top", sa.Float()), sa.Column("bbox_right", sa.Float()), sa.Column("bbox_bottom", sa.Float()), sa.Column("text_span_start", sa.Integer()), sa.Column("text_span_end", sa.Integer()), sa.Column("attribute_type", sa.String(50)), sa.Column("attribute_json", sa.Text()), sa.Column("extensions_json", sa.Text()), sa.PrimaryKeyConstraint("id"), sa.ForeignKeyConstraint(["candidate_id"], ["structured_content_candidates.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["page_id", "candidate_id"], ["structured_content_pages.id", "structured_content_pages.candidate_id"], name="fk_sc_nodes_page_candidate", ondelete="CASCADE"), sa.ForeignKeyConstraint(["parent_node_id", "candidate_id"], ["structured_content_nodes.id", "structured_content_nodes.candidate_id"], name="fk_sc_nodes_parent_candidate", ondelete="RESTRICT"), sa.UniqueConstraint("candidate_id", "node_id", name="uq_sc_nodes_candidate_node_id"), sa.UniqueConstraint("id", "candidate_id", name="uq_sc_nodes_id_candidate"), sa.CheckConstraint("sibling_order >= 0", name="ck_sc_nodes_sibling_order_nonnegative"), sa.CheckConstraint("attribute_type IS NULL OR attribute_type IN ('heading','list','list_item','table','figure','caption','formula')", name="ck_sc_nodes_attribute_type_supported"))
    op.create_index("ix_sc_nodes_candidate_page_sibling", "structured_content_nodes", ["candidate_id", "page_id", "sibling_order"]); op.create_index("ix_sc_nodes_candidate_parent_sibling", "structured_content_nodes", ["candidate_id", "parent_node_id", "sibling_order"])
    op.create_table("structured_content_page_roots", _id(), sa.Column("candidate_id", sa.String(), nullable=False), sa.Column("page_id", sa.String(), nullable=False), sa.Column("node_id", sa.String(), nullable=False), sa.Column("root_order", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id"), sa.ForeignKeyConstraint(["candidate_id"], ["structured_content_candidates.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint(["page_id", "candidate_id"], ["structured_content_pages.id", "structured_content_pages.candidate_id"], name="fk_sc_page_roots_page_candidate", ondelete="CASCADE"), sa.ForeignKeyConstraint(["node_id", "candidate_id"], ["structured_content_nodes.id", "structured_content_nodes.candidate_id"], name="fk_sc_page_roots_node_candidate", ondelete="CASCADE"), sa.UniqueConstraint("page_id", "root_order", name="uq_sc_page_roots_page_order"), sa.UniqueConstraint("page_id", "node_id", name="uq_sc_page_roots_page_node"), sa.CheckConstraint("root_order >= 0", name="ck_sc_page_roots_order_nonnegative"))
    op.create_table("structured_content_evidence", _id(), sa.Column("candidate_id", sa.String(), nullable=False), sa.Column("evidence_id", sa.String(255), nullable=False), sa.Column("kind", sa.String(50), nullable=False), sa.Column("source_file_ref", sa.String(1024)), sa.Column("source_page_index", sa.Integer()), sa.Column("raw_result_ref", sa.String(1024)), sa.Column("structured_processing_result_ref", sa.String(1024)), sa.Column("processing_run_ref", sa.String(1024)), sa.Column("spr_node_ref", sa.String(1024)), sa.Column("spr_observation_ref", sa.String(1024)), sa.Column("spr_evidence_ref", sa.String(1024)), sa.Column("warning_ref", sa.String(1024)), sa.Column("bbox_left", sa.Float()), sa.Column("bbox_top", sa.Float()), sa.Column("bbox_right", sa.Float()), sa.Column("bbox_bottom", sa.Float()), sa.Column("text_span_start", sa.Integer()), sa.Column("text_span_end", sa.Integer()), sa.Column("details_json", sa.Text()), sa.Column("extensions_json", sa.Text()), sa.PrimaryKeyConstraint("id"), sa.ForeignKeyConstraint(["candidate_id"], ["structured_content_candidates.id"], ondelete="CASCADE"), sa.UniqueConstraint("candidate_id", "evidence_id", name="uq_sc_evidence_candidate_evidence_id"), sa.UniqueConstraint("id", "candidate_id", name="uq_sc_evidence_id_candidate"), sa.CheckConstraint("source_page_index IS NULL OR source_page_index >= 0", name="ck_sc_evidence_source_page_index_nonnegative"))
    op.create_table("structured_content_warnings", _id(), sa.Column("candidate_id", sa.String(), nullable=False), sa.Column("warning_id", sa.String(255), nullable=False), sa.Column("code", sa.String(255), nullable=False), sa.Column("severity", sa.String(50), nullable=False), sa.Column("scope_path", sa.String(1024), nullable=False), sa.Column("safe_summary", sa.Text(), nullable=False), sa.Column("recoverable", sa.Boolean(), nullable=False), sa.Column("blocking_hint", sa.Text()), sa.Column("details_json", sa.Text()), sa.Column("extensions_json", sa.Text()), sa.PrimaryKeyConstraint("id"), sa.ForeignKeyConstraint(["candidate_id"], ["structured_content_candidates.id"], ondelete="CASCADE"), sa.UniqueConstraint("candidate_id", "warning_id", name="uq_sc_warnings_candidate_warning_id"), sa.UniqueConstraint("id", "candidate_id", name="uq_sc_warnings_id_candidate"))
    op.create_table("structured_content_assets", _id(), sa.Column("candidate_id", sa.String(), nullable=False), sa.Column("asset_id", sa.String(255), nullable=False), sa.Column("role", sa.String(50), nullable=False), sa.Column("recovery_state", sa.String(50), nullable=False), sa.Column("media_type", sa.String(255)), sa.Column("checksum", sa.String(255)), sa.Column("byte_size", sa.Integer()), sa.Column("width", sa.Float()), sa.Column("height", sa.Float()), sa.Column("dimension_unit", sa.String(50)), sa.Column("source_page_index", sa.Integer()), sa.Column("bbox_left", sa.Float()), sa.Column("bbox_top", sa.Float()), sa.Column("bbox_right", sa.Float()), sa.Column("bbox_bottom", sa.Float()), sa.Column("caption", sa.Text()), sa.Column("alt_text", sa.Text()), sa.Column("description", sa.Text()), sa.Column("storage_ref", sa.String(1024)), sa.Column("extensions_json", sa.Text()), sa.PrimaryKeyConstraint("id"), sa.ForeignKeyConstraint(["candidate_id"], ["structured_content_candidates.id"], ondelete="CASCADE"), sa.UniqueConstraint("candidate_id", "asset_id", name="uq_sc_assets_candidate_asset_id"), sa.UniqueConstraint("id", "candidate_id", name="uq_sc_assets_id_candidate"), sa.CheckConstraint("byte_size IS NULL OR byte_size >= 0", name="ck_sc_assets_byte_size_nonnegative"))
    op.create_table("structured_content_asset_renditions", _id(), sa.Column("asset_id", sa.String(), nullable=False), sa.Column("rendition_id", sa.String(255), nullable=False), sa.Column("rendition_order", sa.Integer(), nullable=False), sa.Column("role", sa.String(50)), sa.Column("media_type", sa.String(255)), sa.Column("storage_ref", sa.String(1024)), sa.Column("checksum", sa.String(255)), sa.Column("width", sa.Float()), sa.Column("height", sa.Float()), sa.Column("dimension_unit", sa.String(50)), sa.Column("recovery_state", sa.String(50)), sa.Column("rebuildable", sa.Boolean(), nullable=False), sa.Column("extensions_json", sa.Text()), sa.PrimaryKeyConstraint("id"), sa.ForeignKeyConstraint(["asset_id"], ["structured_content_assets.id"], ondelete="CASCADE"), sa.UniqueConstraint("asset_id", "rendition_id", name="uq_sc_asset_renditions_asset_rendition_id"), sa.UniqueConstraint("asset_id", "rendition_order", name="uq_sc_asset_renditions_asset_order"), sa.CheckConstraint("rendition_order >= 0", name="ck_sc_asset_renditions_order_nonnegative"))
    op.create_table("structured_content_table_cells", _id(), sa.Column("table_node_id", sa.String(), nullable=False), sa.Column("row_index", sa.Integer(), nullable=False), sa.Column("column_index", sa.Integer(), nullable=False), sa.Column("row_span", sa.Integer(), nullable=False), sa.Column("column_span", sa.Integer(), nullable=False), sa.Column("text", sa.Text()), sa.Column("cell_role", sa.String(50)), sa.Column("extensions_json", sa.Text()), sa.PrimaryKeyConstraint("id"), sa.ForeignKeyConstraint(["table_node_id"], ["structured_content_nodes.id"], ondelete="CASCADE"), sa.UniqueConstraint("table_node_id", "row_index", "column_index", name="uq_sc_table_cells_node_coordinate"), sa.CheckConstraint("row_index >= 0", name="ck_sc_table_cells_row_nonnegative"), sa.CheckConstraint("column_index >= 0", name="ck_sc_table_cells_column_nonnegative"), sa.CheckConstraint("row_span > 0", name="ck_sc_table_cells_row_span_positive"), sa.CheckConstraint("column_span > 0", name="ck_sc_table_cells_column_span_positive"))
    op.create_index("ix_sc_table_cells_node_order", "structured_content_table_cells", ["table_node_id", "row_index", "column_index"])
    for table, left_table, right_table, left_col, right_col in [("structured_content_page_evidence","structured_content_pages","structured_content_evidence","page_id","evidence_id"),("structured_content_page_warning","structured_content_pages","structured_content_warnings","page_id","warning_id"),("structured_content_node_evidence","structured_content_nodes","structured_content_evidence","node_id","evidence_id"),("structured_content_node_asset","structured_content_nodes","structured_content_assets","node_id","asset_id"),("structured_content_node_warning","structured_content_nodes","structured_content_warnings","node_id","warning_id"),("structured_content_asset_evidence","structured_content_assets","structured_content_evidence","asset_id","evidence_id"),("structured_content_warning_evidence","structured_content_warnings","structured_content_evidence","warning_id","evidence_id")]:
        op.create_table(table, _id(), sa.Column(left_col, sa.String(), nullable=False), sa.Column(right_col, sa.String(), nullable=False), sa.Column("association_order", sa.Integer(), nullable=False), sa.PrimaryKeyConstraint("id"), sa.ForeignKeyConstraint([left_col], [f"{left_table}.id"], ondelete="CASCADE"), sa.ForeignKeyConstraint([right_col], [f"{right_table}.id"], ondelete="CASCADE"), sa.UniqueConstraint(left_col, right_col, name=f"uq_{table}"), sa.CheckConstraint("association_order >= 0", name=f"ck_{table}_order_nonnegative"))
    op.create_table("structured_content_selection", sa.Column("document_id", sa.String(), nullable=False), sa.Column("candidate_id", sa.String(), nullable=False), sa.Column("selection_version", sa.Integer(), nullable=False), sa.Column("selected_at", sa.DateTime(), nullable=False), sa.Column("selection_actor_ref", sa.String(255)), sa.Column("reason", sa.Text()), sa.PrimaryKeyConstraint("document_id"), sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="RESTRICT"), sa.ForeignKeyConstraint(["candidate_id", "document_id"], ["structured_content_candidates.id", "structured_content_candidates.document_id"], name="fk_sc_selection_candidate_document", ondelete="RESTRICT"), sa.CheckConstraint("selection_version >= 0", name="ck_sc_selection_version_nonnegative"))


def downgrade() -> None:
    op.drop_table("structured_content_selection")
    for table in ["structured_content_warning_evidence","structured_content_asset_evidence","structured_content_node_warning","structured_content_node_asset","structured_content_node_evidence","structured_content_page_warning","structured_content_page_evidence"]:
        op.drop_table(table)
    op.drop_index("ix_sc_table_cells_node_order", table_name="structured_content_table_cells"); op.drop_table("structured_content_table_cells")
    op.drop_table("structured_content_asset_renditions"); op.drop_table("structured_content_assets"); op.drop_table("structured_content_warnings"); op.drop_table("structured_content_evidence"); op.drop_table("structured_content_page_roots")
    op.drop_index("ix_sc_nodes_candidate_parent_sibling", table_name="structured_content_nodes"); op.drop_index("ix_sc_nodes_candidate_page_sibling", table_name="structured_content_nodes"); op.drop_table("structured_content_nodes")
    op.drop_index("ix_sc_pages_candidate_order", table_name="structured_content_pages"); op.drop_table("structured_content_pages")
    op.drop_index("ix_sc_candidates_lineage_key", table_name="structured_content_candidates"); op.drop_index("ix_sc_candidates_document_id", table_name="structured_content_candidates"); op.drop_table("structured_content_candidates")
